# Generated by Django 5.1.4 on 2024-12-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('users', models.CharField(max_length=100)),
                ('ts_id', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('passwords', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('sect', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='work',
        ),
    ]
