# Generated by Django 5.1.4 on 2024-12-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_section_use_delete_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Are',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('s_lname', models.CharField(max_length=100)),
                ('s_id', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
