# Generated by Django 5.1.4 on 2025-02-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_rename_password_are_passwordss_rename_s_id_are_t_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='are',
            name='id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='id',
        ),
        migrations.RemoveField(
            model_name='use',
            name='id',
        ),
        migrations.AlterField(
            model_name='are',
            name='t_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='use',
            name='users',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
